### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by GeorvityLabs** [TencentYoutuResearch/3DFaceReconstruction-LAP#8]
Hey guys,

I made a colab notebook for this project.
I'm currently getting this error

`Traceback (most recent call last):
  File "demo.py", line 341, in <module>
    model = Demo(args)
  File "demo.py", line 53, in __init__
    self.renderer_mr = Renderer(cfgs, im_size=128)
  File "/content/3DFaceReconstruction-LAP/lap/renderer/renderer_mr.py", line 45, in __init__
    self.inv_k_mat = torch.inverse(k_mat).unsqueeze(0)
RuntimeError: CUDA error: invalid device function`

How to fix this?

Here is a link to my notebook , you can make a copy and edit it 

https://colab.research.google.com/drive/18tIkvLIaN-_v3sLW2ykkcLGpqxwRN13z?usp=sharing

**Comment by cuizhanyuan** [comment]
Just delete." import torch; torch.__version__".

**Comment by GeorvityLabs** [comment]
@cuizhanyuan that doesn't fix the error.

Still getting :
Traceback (most recent call last):
  File "demo.py", line 341, in <module>
    model = Demo(args)
  File "demo.py", line 53, in __init__
    self.renderer_mr = Renderer(cfgs, im_size=128)
  File "/content/3DFaceReconstruction-LAP/lap/renderer/renderer_mr.py", line 45, in __init__
    self.inv_k_mat = torch.inverse(k_mat).unsqueeze(0)
RuntimeError: CUDA error: invalid device function

Link to colab , please run and check it yourself!
https://colab.research.google.com/drive/18tIkvLIaN-_v3sLW2ykkcLGpqxwRN13z?usp=sharing

**Comment by cuizhanyuan** [comment]
I don't know what to do. I commented out that part yesterday and it worked. Today it failed.
